os: linux
dist: xenial
language: cpp
compiler: clang
install:
  - pip install --user conan
  - conan user
script:
  - conan install .
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - ls
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uilia64:$BINTRAY_KEY "https://api.bintray.com/content/ilia64/otus-cpp/range/$TRAVIS_BUILD_NUMBER/range-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
